#!/bin/bash -e

HOMEBREW_TAP_PATH=./.build/homebrew-tap
FILENAME="$APP_NAME-$APP_VSN.tar.gz"

# Cleanup potential old builds and reclone the tap repo
rm -rf $HOMEBREW_TAP_PATH
mkdir -p $HOMEBREW_TAP_PATH
git clone git@github.com:Shimmur/homebrew-tap.git $HOMEBREW_TAP_PATH

# Create tar of app
tar cvzf "$FILENAME" ./$APP_NAME
SHA256SUM=$(sha256sum $FILENAME | awk '{ print $1 }')

# Release to homebrew-tap
cat << EOF > $HOMEBREW_TAP_PATH/Formula/$APP_NAME.rb 
# typed: false
# frozen_string_literal: true

# This file was generated by Makefile. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class NmesosK8s < Formula
  desc "Converts nmesos manifests to kubernetes manifests"
  homepage ""
  version "$APP_VSN"

  on_macos do
    url "https://github.com/Shimmur/$APP_NAME/releases/download/$APP_VSN/$FILENAME", using: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "$SHA256SUM"

    def install
      bin.install "$APP_NAME"
    end

    if Hardware::CPU.arm?
      url "https://github.com/Shimmur/$APP_NAME/releases/download/$APP_VSN/$FILENAME", using: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "$SHA256SUM"

      def install
        bin.install "$APP_NAME"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Shimmur/$APP_NAME/releases/download/$APP_VSN/$FILENAME", using: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "$SHA256SUM"

      def install
        bin.install "$APP_NAME"
      end
    end
  end
end
EOF

# Deploy release to github
gh release create $APP_VSN --generate-notes ./$FILENAME

# Push homebrew formula to github
cd $HOMEBREW_TAP_PATH
git add ./Formula/$APP_NAME.rb
git commit -m "Brew formula update for $APP_NAME version $APP_VSN" 
git push

# Push new version to s3 version object
echo "$APP_VSN" | aws s3 cp - s3://community-platform-nmesos-k8s-version/version
